import React, { useState } from "react";
import { StyledHorizontalBlinds } from "./styled/StyledHorizontalBlinds";

export default function HorizontalBlinds({ changeMode }) {
  const [change, setChange] = useState(false);
  const [dark, setDark] = useState(true);
  function switcher() {
    setChange(!change);
	setDark(!dark);
	changeMode();
  }

  return (
    <StyledHorizontalBlinds onClick={switcher} change={change} dark={dark}>
      <figure id="blinds">
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://imagenes.20minutos.es/files/article_amp/uploads/2020/06/19/rick-astley-en-su-cancion-never-gonna-give-you-up.gif"
          alt
          class="first"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
        <img
          src="https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/16:9/w_1920,c_limit/rickrolling_3543.png"
          alt
          class="second"
        />
      </figure>
    </StyledHorizontalBlinds>
  );
}
